### ISSUE TITLE
return_fig regression

### ISSUE THREAD

**Issue by PedroMartinSteenstrup** [transferwise/wise-pizza#35]
Might be confused there as I just started looking into Wise-pizza, but I understand `return_fig` was added here
https://github.com/transferwise/wise-pizza/pull/17

It exists in the plot functions with a default of False 
https://github.com/transferwise/wise-pizza/blob/1d870df5d8619f9bad676aaedb4d07221ab359a8/wise_pizza/plotting.py#L26

I feel somewhere around revision [ 5772636575d548adcf12bafa438c164bde78a193](https://github.com/transferwise/wise-pizza/commit/5772636575d548adcf12bafa438c164bde78a193) it got lost from the signature of `explain_changes_in_totals` for example

Will keep looking, but just flagging in case that wasn't intentional

**Comment by AlxdrPolyakov** [comment]
Hey thanks a lot! We use **return_fig** parameter only to show plots in the **streamlit**. That's why we don't choose it in the main functions. Let us know if you really need it in the explain functions.
