### ISSUE TITLE
Understand Wize pizza graphs and invalid columns error

### ISSUE THREAD

**Issue by Arnold2381** [transferwise/wise-pizza#39]
Hi,
I just wanted understand how is the Segment averages and global average calculated?

Also I am seeing this error

```
/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/wise_pizza/slicer.py:167: FutureWarning:

Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the function.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[69], line 1
----> 1 sf = explain_levels(
      2     df=df,
      3     dims=dims,
      4     total_name=totals,
      5     max_depth=2,
      6     min_segments=20,
      7     solver="lasso",
      8     cluster_values=True
      9 )

TypeError: sequence item 0: expected str instance, float found


```

**Comment by EgorKraevTransferwise** [comment]
@Arnold2381, the segment average is the sum of totals for the respective segment, divided by the sum of weights for that same segment. Likewise, the global average is the sum of all totals divided by the sum of all weights.

Regarding the error, it's not one I've seen before. Could you possibly post some code to allow us to reproduce? 
You could use this synthetic dataset https://github.com/transferwise/wise-pizza/blob/a02f1e2275f6425d1e86f52579d2846f59dd4cc6/wise_pizza/data_sources/synthetic.py#L11 to apply your code to, for example.

**Comment by AlxdrPolyakov** [comment]
Hey I think this error is caused by passing float columns to dims columns. If this is the case, you should use string or int.
